console.log("Hello World!");
console.log("");
console.log("Favorite Websites:");
console.log("1. dndbeyond.com");
console.log("2. youtube.com");
console.log("3. netflix.com");
console.log("");
console.log("Favorite Games:");
console.log("1. Super Mario Galaxy");
console.log("2. Bravely Default");
console.log("3. Fire Emblem");
console.log("");
console.log("Favorite Artists:");
console.log("1. Jeff Koons, whose sculptures gave a lot of insight into what makes high art and what makes commercialized art in the 20th century.");
console.log("2. Marcel Duchamp, whose untraditional sculpture 'The Fountain' shook the world in 1917. ");
console.log("3. Andy Warhol, who was a prolific figure in the era of Pop Art.");
